Feature/service batch
vinidomeli/tlm-frescos-api pull request #34
Opened 2021-07-03 15:34 UTC by luana-ogawa

2021-07-03 17:19 UTC, andradeirla reviewed
Corrigido para os arquivos específicos.

2021-07-03 17:30 UTC, andradeirla commented on src/main/java/com/mercadolibre/dambetan01/dtos/BatchStockDTO.java
> +    private Long productId;
Não seria o UUID que foi definido para os atributos que estavam como String no JSON do PDF do requisito 1 e Long para os que estavam como int?

2021-07-03 17:30 UTC, andradeirla commented on src/main/java/com/mercadolibre/dambetan01/repository/ProductRepository.java
>  public interface ProductRepository extends JpaRepository<Product, Long> {
Nesse também UUID que se refere ao anterior.

2021-07-05 12:33 UTC, vinidomeli requested changes

2021-07-05 12:33 UTC, vinidomeli commented on src/main/java/com/mercadolibre/dambetan01/config/WebSecurityConfig.java
>  @EnableWebSecurity
Não seria uma boa fazer o checkout deste arquivo? A ideia da edição era mais para testes

2021-07-06 14:27 UTC, luana-ogawa commented on src/main/java/com/mercadolibre/dambetan01/dtos/BatchStockDTO.java
> +    private Long productId;
aqui optamos por deixar como estava na criação da tabela

2021-07-06 14:27 UTC, luana-ogawa commented on src/main/java/com/mercadolibre/dambetan01/repository/ProductRepository.java
>  public interface ProductRepository extends JpaRepository<Product, Long> {
Aqui optamos por deixar como estava na criação da tabela

2021-07-06 15:06 UTC, luana-ogawa commented on src/main/java/com/mercadolibre/dambetan01/config/WebSecurityConfig.java
>  @EnableWebSecurity
Okay, checkout feito

2021-07-06 15:07 UTC, vinidomeli approved these changes

2021-07-06 15:19 UTC, andradeirla approved these changes

2021-07-06 15:21 UTC, merged