Feature/req1 unit testing
vinidomeli/tlm-frescos-api pull request #59
Opened 2021-07-07 17:50 UTC by luana-ogawa

2021-07-07 19:06 UTC, vinidomeli requested changes

2021-07-07 19:06 UTC, vinidomeli commented on src/main/java/com/mercadolibre/dambetan01/config/WebSecurityConfig.java
>  public class WebSecurityConfig extends WebSecurityConfigurerAdapter {
Não seria uma boa dar checkout neste arquivo? Para mantermos o padrao dos filtros

2021-07-08 16:59 UTC, luana-ogawa commented on src/main/java/com/mercadolibre/dambetan01/config/WebSecurityConfig.java
>  public class WebSecurityConfig extends WebSecurityConfigurerAdapter {
feito

2021-07-08 18:13 UTC, andradeirla approved these changes

2021-07-08 18:28 UTC, igor-smascarenhas approved these changes

2021-07-08 18:43 UTC, vinidomeli approved these changes

2021-07-08 18:44 UTC, merged